/**
 * قاموس ترجمة أسماء حقول التقارير المالية (snake_case) → عربي.
 * مبني على الـ Response الحقيقي لتقارير: daily-safe, shift-safe, financial-summary,
 * departments, doctors, expenses-salaries, transactions-ledger.
 * لو ظهر key جديد (خصوصًا من تقرير devices اللي لسه ملوش مثال) وطلع إنجليزي،
 * ابعتيه وهضيفه هنا في مكان واحد بس.
 */
export const REPORT_LABELS: Record<string, string> = {
  // ===== عام / وصفي =====
  report_title: "عنوان التقرير",
  report_date: "تاريخ التقرير",
  period: "الفترة",
  start_date: "من تاريخ",
  end_date: "إلى تاريخ",
  days_count: "عدد الأيام",
  id: "الرقم",
  name: "الاسم",
  title: "العنوان",
  description: "الوصف",
  notes: "ملاحظات",
  status: "الحالة",
  unit: "الوحدة",
  currency: "العملة",
  created_at: "تاريخ الإنشاء",
  updated_at: "تاريخ التحديث",
  count: "العدد",
  revenue: "الإيراد",
  amount: "المبلغ",
  price: "السعر",
  percent: "النسبة %",
  type: "النوع",
  type_arabic: "وصف النوع",

  // ===== ملخص الخزنة (daily-safe / shift-safe) =====
  shifts_count: "عدد الشفتات",
  treasury_summary: "ملخص الخزنة",
  opening_balance: "الرصيد الافتتاحي",
  cash_collected: "النقدي المُحصّل",
  visa_collected: "الفيزا/الشبكة المُحصّلة",
  wallet_collected: "المحفظة الإلكترونية المُحصّلة",
  insurance_collected: "التأمين المُحصّل",
  total_collected_revenue: "إجمالي الإيراد المُحصّل",
  cash_expenses_paid: "مصروفات نقدية مدفوعة",
  non_cash_expenses: "مصروفات غير نقدية",
  cash_refunds_paid: "مرتجعات نقدية مدفوعة",
  non_cash_refunds: "مرتجعات غير نقدية",
  total_cash_outflows: "إجمالي المنصرف النقدي",
  expected_drawer_balance: "الرصيد المتوقع بالدرج",
  actual_drawer_balance: "الرصيد الفعلي بالدرج",
  difference: "الفرق",
  difference_status: "حالة الفرق",
  status_note: "ملاحظة الحالة",
  difference_note: "ملاحظة الفرق",

  // ===== تفاصيل العمليات =====
  operations_breakdown: "تفاصيل العمليات",
  total_invoices_issued: "إجمالي الفواتير الصادرة",
  consultations_count: "عدد الكشوفات",
  services_count: "عدد الخدمات",
  devices_count: "عدد جلسات الأجهزة",
  direct_sales_count: "عدد المبيعات المباشرة",
  unique_patients_count: "عدد المرضى الفريدين",
  expenses_count: "عدد المصروفات",
  refunds_count: "عدد المرتجعات",

  // ===== الشفتات =====
  shifts: "الشفتات",
  shift_id: "رقم الشفت",
  employee_id: "رقم الموظف",
  employee_name: "اسم الموظف",
  employee_phone: "هاتف الموظف",
  start_time: "وقت البداية",
  end_time: "وقت النهاية",
  duration_hours: "مدة الشفت (ساعات)",
  is_late: "متأخر؟",
  late_minutes: "دقائق التأخير",
  overtime_minutes: "دقائق الأوفرتايم",
  opening_latitude: "خط العرض عند الفتح",
  opening_longitude: "خط الطول عند الفتح",
  initial_balance: "الرصيد الافتتاحي",
  total_revenue: "إجمالي الإيراد",
  total_cash_outflow: "إجمالي المنصرف النقدي",
  expected_cash: "النقدي المتوقع",
  actual_cash: "النقدي الفعلي",

  // ===== الحركات التفصيلية =====
  detailed_movements: "الحركات التفصيلية",
  timestamp: "التوقيت",
  time_formatted: "الوقت",
  cashier_name: "اسم الكاشير",
  movement_type: "نوع الحركة",
  ref_number: "رقم المرجع",
  patient_name: "اسم المريض",
  doctor_name: "اسم الطبيب",
  payment_method: "طريقة الدفع",
  inflow: "وارد",
  outflow: "منصرف",

  // ===== التقرير المالي الشامل (P&L) =====
  bottom_line_profit: "صافي الربح النهائي",
  net_profit_amount: "قيمة صافي الربح",
  net_profit_margin_percent: "هامش صافي الربح %",
  performance_status: "حالة الأداء",
  financial_health: "الحالة المالية",
  profit_per_day: "الربح لكل يوم",
  profit_per_patient: "الربح لكل مريض",
  income_statement: "قائمة الدخل",
  revenues: "الإيرادات",
  gross_invoiced: "إجمالي الفواتير",
  discounts_given: "الخصومات الممنوحة",
  net_invoiced: "صافي الفواتير",
  refunds_deducted: "المرتجعات المخصومة",
  net_realized_revenue: "صافي الإيراد المحقق",
  by_category: "حسب الفئة",
  consultations: "الكشوفات",
  services: "الخدمات",
  devices: "الأجهزة",
  direct_sales: "المبيعات المباشرة",
  collection_breakdown: "تفاصيل التحصيل",
  cash: "نقدي",
  visa: "فيزا/شبكة",
  wallet: "محفظة إلكترونية",
  insurance: "تأمين",
  total_collected: "إجمالي المُحصّل",
  remaining_uncollected: "المتبقي غير المُحصّل",
  collection_rate_pct: "نسبة التحصيل %",
  cost_of_supplies_cogs: "تكلفة المستلزمات (COGS)",
  total_cogs_amount: "إجمالي تكلفة المستلزمات",
  gross_profit: "إجمالي الربح",
  gross_profit_margin_pct: "هامش إجمالي الربح %",
  operating_expenses: "المصروفات التشغيلية",
  total_expenses_amount: "إجمالي المصروفات",
  payroll_and_salaries: "الرواتب والأجور",
  total_salaries_paid: "إجمالي الرواتب المدفوعة",
  payrolls_count: "عدد كشوف المرتبات",
  total_clinic_expenditures: "إجمالي مصروفات العيادة",
  net_operating_profit: "صافي الربح التشغيلي",
  operational_kpis: "مؤشرات الأداء التشغيلية",
  total_unique_patients: "إجمالي المرضى الفريدين",
  average_invoice_value: "متوسط قيمة الفاتورة",
  average_revenue_per_day: "متوسط الإيراد اليومي",

  // ===== تقرير الأقسام =====
  clinic_overview: "نظرة عامة على العيادة",
  total_clinic_revenue: "إجمالي إيراد العيادة",
  total_departments: "إجمالي الأقسام",
  total_consultations: "إجمالي الكشوفات",
  total_services: "إجمالي الخدمات",
  total_devices_sessions: "إجمالي جلسات الأجهزة",
  departments: "الأقسام",
  department_id: "رقم القسم",
  department_name: "اسم القسم",
  revenue_share_percent: "نسبة المساهمة في الإيراد %",
  invoices_count: "عدد الفواتير",
  patients_count: "عدد المرضى",
  operations_summary: "ملخص العمليات",
  top_3_doctors: "أعلى 3 أطباء",
  doctor_id: "رقم الطبيب",
  doctor_phone: "هاتف الطبيب",
  consultations_revenue: "إيراد الكشوفات",
  services_revenue: "إيراد الخدمات",
  devices_revenue: "إيراد الأجهزة",
  total_cases_count: "إجمالي عدد الحالات",
  doctor_commission: "عمولة الطبيب",
  clinic_net_share: "صافي نصيب العيادة",
  rank: "الترتيب",
  rank_badge: "وسام الترتيب",
  all_doctors_count: "إجمالي عدد الأطباء",

  // ===== تقرير الأطباء =====
  doctors_count: "عدد الأطباء",
  aggregate_summary: "الملخص الإجمالي",
  total_revenue_all_doctors: "إجمالي إيراد كل الأطباء",
  total_commissions_all_doctors: "إجمالي عمولات كل الأطباء",
  total_clinic_net_share: "إجمالي صافي نصيب العيادة",
  contract_type: "نوع العقد",
  metrics: "المؤشرات",
  follow_ups_count: "عدد المتابعات",
  total_patients_treated: "إجمالي المرضى المعالَجين",
  total_invoices_count: "إجمالي عدد الفواتير",
  financial_performance: "الأداء المالي",
  total_revenue_generated: "إجمالي الإيراد المحقق",
  doctor_commission_dues: "مستحقات عمولة الطبيب",
  clinic_margin_percent: "هامش ربح العيادة %",
  services_rendered: "الخدمات المقدَّمة",
  service_id: "رقم الخدمة",
  service_name: "اسم الخدمة",
  unit_price: "سعر الوحدة",
  overall_rank: "الترتيب العام",

  // ===== المصروفات والرواتب =====
  grand_total_spent: "إجمالي المنصرف الكلي",
  total_expenses: "إجمالي المصروفات",
  total_combined_outflows: "إجمالي المنصرف (مصروفات + رواتب)",
  expenses_section: "قسم المصروفات",
  expenses_vouchers_count: "عدد إيصالات الصرف",
  cash_paid_from_drawer: "المدفوع نقدًا من الدرج",
  non_cash_paid: "المدفوع بغير النقدي",
  category_code: "كود الفئة",
  category_name: "اسم الفئة",
  total_amount: "إجمالي المبلغ",
  itemized_expenses: "تفاصيل المصروفات",
  salaries_section: "قسم الرواتب",
  total_net_salaries_paid: "إجمالي صافي الرواتب المدفوعة",
  total_gross_salaries: "إجمالي الرواتب الإجمالية",
  total_deductions: "إجمالي الخصومات",
  payrolls_paid_count: "عدد كشوف المرتبات المدفوعة",
  components_breakdown: "تفاصيل المكوّنات",
  basic_salaries: "الرواتب الأساسية",
  service_commissions: "عمولات الخدمات",
  device_commissions: "عمولات الأجهزة",
  product_commissions: "عمولات المنتجات",
  overtime_paid: "الأوفرتايم المدفوع",
  holiday_allowances_paid: "بدلات الإجازات المدفوعة",
  target_bonuses_paid: "مكافآت التارجت المدفوعة",
  itemized_payrolls: "تفاصيل كشوف المرتبات",

  // ===== سجل الحركات المالية =====
  movements_count: "عدد الحركات",
  ledger_totals: "إجمالي الحركات",
  total_debits_inflows: "إجمالي الوارد (مدين)",
  total_credits_outflows: "إجمالي المنصرف (دائن)",
  net_cash_flow: "صافي التدفق النقدي",
  ledger_movements: "حركات السجل",
  category: "الفئة",
  party_name: "اسم الطرف",
  doctor_or_staff: "الطبيب/الموظف",
  recorded_by: "سُجّلت بواسطة",
  debit: "مدين",
  credit: "دائن",
  net_flow: "صافي الحركة",
  running_balance: "الرصيد الجاري",
};

/**
 * ترجمة قيم شائعة (حالات/أنواع) بتظهر كـ value مش كـ key، عشان الجدول
 * يبقى عربي بالكامل مش بس عناوين الأعمدة.
 */
export const REPORT_VALUE_LABELS: Record<string, string> = {
  balanced: "مضبوط",
  surplus: "زيادة",
  shortage: "عجز",
  open: "مفتوح",
  closed: "مغلق",
  profit: "ربح",
  loss: "خسارة",
  income: "إيراد",
  opening_balance: "رصيد افتتاحي",
  cash: "كاش",
  visa: "فيزا/شبكة",
  wallet: "محفظة إلكترونية",
  insurance: "تأمين",
  consultation: "كشف",
  direct_sale: "بيع مباشر",
  service: "خدمة",
  device: "جهاز",
};

/**
 * ترجم اسم الحقل لعربي لو موجود في القاموس، وإلا يرجّع الاسم منسّق زي ما هو.
 */
export const translateKey = (key: string): string => {
  const normalized = key.toLowerCase();
  if (REPORT_LABELS[normalized]) return REPORT_LABELS[normalized];
  return key.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
};

/**
 * ترجم قيمة نصية معروفة (status/type) لعربي، وإلا يرجّعها زي ما هي.
 */
export const translateValue = (value: string): string => {
  const normalized = value.toLowerCase();
  return REPORT_VALUE_LABELS[normalized] ?? value;
};